#!/usr/bin/env bash

! type >/dev/null 2>&1 realpath && function realpath() {
  python3 -c 'import sys,os.path; [print(os.path.realpath(v)) for v in list(sys.argv)[1:]]'
}

function git-at() {
  if [[ $# -lt 1 ]]; then
    command cat <<EOF 1>&2
  $(basename "$0") <repo_dirpath> [commands]...
EOF
    return 1
  fi

  local repo_dir=$1
  shift
  local git_repo_dir
  git_repo_dir="$(realpath "$repo_dir")"
  local dot_git_dir
  dot_git_dir="$(realpath "$repo_dir/.git")"
  git --git-dir "$dot_git_dir" -C "$git_repo_dir" "$@"
}

git-at "$@"
